name: unit tests

on:
  workflow_call:
    inputs:
      parent-ref:
        type: string
        required: true
      parent-repo:
        type: string
        required: true

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "hello from target release!"
          echo "parent ref: ${PARENT_REF}"
          echo "parent repo: $PARENT_REPO"
          echo "ref: $HEAD_REF"
          echo "repo: $REPO"
        env:
          PARENT_REF: ${{ inputs.parent-ref }}
          PARENT_REPO: ${{ inputs.parent-repo }}
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
          REPO: ${{ github.event.pull_request.head.repo.full_name }}
